version: "3"
services:
  postgresql:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: "pharmix"
      POSTGRES_PASSWORD: "pharmix"
      POSTGRES_DB: "pharmix"
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data